In [1]:
import pandas as pd

In [2]:
data = {
    "Education":["Graduate","Graduate","Postgraduate","Postgraduate","Undergraduate","Undergraduate"],
    "Income":[30000,32000,40000,45000,34000,36000]
}

In [3]:
df = pd.DataFrame(data)
df

       Education  Income
0       Graduate   30000
1       Graduate   32000
2   Postgraduate   40000
3   Postgraduate   45000
4  Undergraduate   34000
5  Undergraduate   36000

In [4]:
summary_statistics = df.groupby("Education")["Income"].agg(
    Mean = "mean",
    Median = "median",
    Minimum = "min",
    Maximum = "max",
    Standard_Deviation = "std"
)

In [5]:
summary_statistics

                  Mean   Median  Minimum  Maximum  Standard_Deviation
Education
Graduate       31000.0  31000.0    30000    32000         1414.213562
Postgraduate   42500.0  42500.0    40000    45000         3535.533906
Undergraduate  35000.0  35000.0    34000    36000         1414.213562

In [6]:
income_list = df.groupby("Education")["Income"].agg(list).to_dict()
display(income_list)

{'Graduate': [30000, 32000],
 'Postgraduate': [40000, 45000],
 'Undergraduate': [34000, 36000]}

In [7]:
df1 = pd.read_csv("Iris (3).csv")

In [8]:
df1.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [9]:
df1['SepalLengthCm'].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

In [10]:
df1['SepalWidthCm'].describe()

count    150.000000
mean       3.054000
std        0.433594
min        2.000000
25%        2.800000
50%        3.000000
75%        3.300000
max        4.400000
Name: SepalWidthCm, dtype: float64

In [11]:
newdf = df1.groupby("Species")
newdf

In [12]:
df1.SepalLengthCm.std()

np.float64(0.828066127977863)

In [13]:
df1.SepalLengthCm.min()

np.float64(4.3)

In [14]:
df1.groupby(['Species']).count()

                 Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa      50             50            50             50            50
Iris-versicolor  50             50            50             50            50
Iris-virginica   50             50            50             50            50

In [16]:
df1.groupby("Species").describe().sum()

Id             count    150.000000
               mean     226.500000
               std       43.732139
               min      153.000000
               25%      189.750000
               50%      226.500000
               75%      263.250000
               max      300.000000
SepalLengthCm  count    150.000000
               mean      17.530000
               std        1.504540
               min       14.100000
               25%       16.625000
               50%       17.400000
               75%       18.400000
               max       20.700000
SepalWidthCm   count    150.000000
               mean       9.162000
               std        1.017319
               min        6.500000
               25%        8.450000
               50%        9.200000
               75%        9.850000
               max       11.600000
PetalLengthCm  count    150.000000
               mean      11.276000
               std        1.195317
               min        8.500000
               25%       10.500000
               50%       11.400000
               75%       12.050000
               max       13.900000
PetalWidthCm   count    150.000000
               mean       3.596000
               std        0.579612
               min        2.500000
               25%        3.200000
               50%        3.500000
               75%        4.100000
               max        4.900000
dtype: float64

In [17]:
df1.groupby("Species").describe()

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]